
spring.data.mongodb.uri=mongodb+srv://billucoder586_db_user:SjtwdN4nnPUnfmyp@cluster0.syedjw1.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=application
spring.data.mongodb.auto-index-creation=true

